name: Update Progress Bar

on:
  push:
    paths:
      - 'README.md'
      - '.github/scripts/progress-bar.py'
  workflow_dispatch:

permissions:
 contents: write

jobs:
  update-readme-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run progress bar update script
        run: python .github/scripts/progress-bar.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update progress bar badge [auto]" || echo "No changes to commit"
          git push
